### ISSUE TITLE
Polling 2013 sample has an ambiguous reference

### ISSUE THREAD

**Issue by cecilphillip** [Telligent/Telligent-Community-Samples#1]
```
'Poll' is an ambiguous reference between 'Telligent.BigSocial.Polling.InternalApi.Poll' and 'Telligent.Evolution.Extensibility.Api.Entities.Version1.Poll'

C:\Dev\Projects\TelligentPolling2013\Telligent-Community-Samples\applications\Polling2013\Telligent.BigSocial.Polling\Plugins\PollingApplication.cs 531 13  Telligent.BigSocial.Polling
```

I had to use the FQDN to get it to compile
`Telligent.BigSocial.Polling.InternalApi.Poll`

**Comment by pmason127** [comment]
What version of Telligent Community was this

**Comment by cecilphillip** [comment]
whatever version gets retrieved from the "Get Free Edition Page". I downloaded it last Friday

**Comment by pmason127** [comment]
Good enough :)   I will have someone look into fixing it but your solution is appropriate.  This is more than likely because this was developed for earlier versions and we have since added Poll functionality to the product so the 2 namespaces confuse it.
